"use strict";
const React = require('react');
class Tongji extends React.Component {
    render() {
        return (React.createElement("div", {className: "mcon3"}, 
            React.createElement("div", {className: "mc2_t"}, "党内统计信息"), 
            React.createElement("div", {className: "mc3Box"}, 
                React.createElement("div", {className: "hd"}, 
                    React.createElement("ul", null, 
                        React.createElement("li", {className: "on"}, "党员及党组织 建设情况"), 
                        React.createElement("li", null, "党员队伍情况"), 
                        React.createElement("li", null, "发展党员情况"), 
                        React.createElement("li", null, "申请入党情况"), 
                        React.createElement("li", null, "党员组织情况"))
                ), 
                React.createElement("div", {className: "bd"}, 
                    React.createElement("div", {className: "mc3Con"}, 
                        React.createElement("div", {className: "mc3L"}, 
                            React.createElement("div", {className: "mc3_st"}, "党员的性别、民族、学历"), 
                            React.createElement("ul", null, 
                                React.createElement("li", null, 
                                    React.createElement("img", {src: "/assets/images/hm_bmicon1.jpg", width: "76", height: "76"}), 
                                    React.createElement("div", {className: "mc3_nm"}, "32.6%"), 
                                    React.createElement("div", {className: "mc3_s1"}, "女党员"), 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名")), 
                                React.createElement("li", null, 
                                    React.createElement("img", {src: "/assets/images/hm_bmicon2.jpg", width: "76", height: "76"}), 
                                    React.createElement("div", {className: "mc3_nm"}, "32.6%"), 
                                    React.createElement("div", {className: "mc3_s1"}, "少数名族党员"), 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名")), 
                                React.createElement("li", null, 
                                    React.createElement("img", {src: "/assets/images/hm_bmicon3.jpg", width: "76", height: "76"}), 
                                    React.createElement("div", {className: "mc3_nm"}, "32.6%"), 
                                    React.createElement("div", {className: "mc3_s1"}, "大专以上学历党员"), 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名")))), 
                        React.createElement("div", {className: "mc3R"}, 
                            React.createElement("div", {className: "mc3_st mc3_st2"}, "党员的性别、民族、学历"), 
                            React.createElement("div", {className: "mc3r_od"}, 
                                React.createElement("span", {className: "mc3r_s"}, "24及以下党员"), 
                                React.createElement("div", {className: "mc3r_box"}, 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名"), 
                                    React.createElement("div", {className: "mc3_lg"}, 
                                        React.createElement("span", {style: { width: "89.0%" }})
                                    )), 
                                React.createElement("span", {className: "mc3r_s"}, "占党员总数89.0%")), 
                            React.createElement("div", {className: "mc3r_od"}, 
                                React.createElement("span", {className: "mc3r_s"}, "24及以下党员"), 
                                React.createElement("div", {className: "mc3r_box"}, 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名"), 
                                    React.createElement("div", {className: "mc3_lg"}, 
                                        React.createElement("span", {style: { width: "89.0%" }})
                                    )), 
                                React.createElement("span", {className: "mc3r_s"}, "占党员总数89.0%")), 
                            React.createElement("div", {className: "mc3r_od"}, 
                                React.createElement("span", {className: "mc3r_s"}, "24及以下党员"), 
                                React.createElement("div", {className: "mc3r_box"}, 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名"), 
                                    React.createElement("div", {className: "mc3_lg"}, 
                                        React.createElement("span", {style: { width: "89.0%" }})
                                    )), 
                                React.createElement("span", {className: "mc3r_s"}, "占党员总数89.0%")), 
                            React.createElement("div", {className: "mc3r_od"}, 
                                React.createElement("span", {className: "mc3r_s"}, "24及以下党员"), 
                                React.createElement("div", {className: "mc3r_box"}, 
                                    React.createElement("div", {className: "mc3_s2"}, 
                                        React.createElement("span", {className: "cor_red"}, "XXX"), 
                                        "万名"), 
                                    React.createElement("div", {className: "mc3_lg"}, 
                                        React.createElement("span", {style: { width: "89.0%" }})
                                    )), 
                                React.createElement("span", {className: "mc3r_s"}, "占党员总数89.0%"))), 
                        React.createElement("div", {className: "clear"}))
                ), 
                React.createElement("div", {className: "clear"}))));
    }
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Tongji;
//# sourceMappingURL=tongji.js.map